for p in ["vagrant-aws","vagrant-puppet-install"] do
  unless Vagrant.has_plugin?("#{p}")
    raise "#{p} plugin required! Please run 'vagrant plugin install #{p}'"
  end
end

$box_vbox = "kmm/ubuntu-xenial64"
machine_name = "ubuntu-1604-base"
Vagrant.configure("2") do |config|
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.vm.boot_timeout = 120

  config.vm.provider :virtualbox do |vb|
    vb.name = machine_name
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id,"--memory", "4096"]
  end
  config.vm.box = $box_vbox
  # disable upgrade-check service before installing puppet
  # otherwise dpkg is locked.
  config.vm.provision :shell, :path => "../scripts/disable-unattended-upgrades.sh"
  config.puppet_install.puppet_version = "5.3.3"
  config.vm.provision :shell do |s|
    s.path = "../scripts/install-puppet-modules.sh"
    s.args = ["puppetlabs-stdlib",
              "puppetlabs-apt",
              "puppetlabs-java",
              "elastic-elasticsearch",
              "elastic-kibana"]
  end
end
