load File.expand_path('../Vagrantfile.setup', __FILE__)

Vagrant.configure(2) do |config|
  config.vm.box = $box
  config.vm.box_url = $box_url
  # setup each machine.
  ec2_instance = "jenkins-nexus-tomcat-docker"
  config.vm.define ec2_instance do |config2|

      # custom config block for AWS provider.
    config2.vm.provider :aws do |ec2, override|
        ec2.keypair_name = $keypair_name
        ec2.access_key_id = $access_key_id
        ec2.secret_access_key = $secret_access_key
        ec2.security_groups = $security_groups
        override.ssh.private_key_path = $private_key_path
        ec2.region = $ec2_region
        ec2.availability_zone = $ec2_zone
        ec2.ami = $ec2_ami
        ec2.instance_type = $ec2_instance
        override.ssh.username = $ec2_username
        ec2.tags = {
          'Name'         => "#{ec2_instance}"
        }
    end
  end
end
