Vagrant.configure('2') do |config|
    config.vm.box = 'azure'
    config.vm.box_url = 'https://github.com/azure/vagrant-azure/raw/v2.0/dummy.box'
    # use local ssh key to connect to remote vagrant box
    config.ssh.private_key_path = '~/.ssh/id_rsa'

    config.vm.provider :azure do |azure, override|
        azure.tenant_id = ENV['AZURE_TENANT_ID']
        azure.client_id = ENV['AZURE_CLIENT_ID']
        azure.client_secret = ENV['AZURE_CLIENT_SECRET']
        azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
        azure.vm_name = "csubuntu"
        azure.vm_size = "Standard_DS1_v2"
        azure.admin_username = "azureuser"
        azure.vm_image_urn = 'canonical:ubuntuserver:16.04-LTS:latest'
        azure.location = "westus"
    end

end